# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost # Assume localhost como padrão, será sobrescrito em produção

development:
  <<: *default
  database: catalogo_filmes_development
  username: felipe # O usuário do banco de dados para o ambiente de desenvolvimento
  # Para o ambiente de desenvolvimento, a senha é opcional se não configurada no PostgreSQL local.
  # Usamos ENV.fetch com um valor padrão para evitar erros se a variável não estiver definida.
  password: <%= ENV.fetch("DB_PASSWORD_DEVELOPMENT", "") %> # Use ENV["DB_PASSWORD_DEVELOPMENT"] ou vazio

test:
  <<: *default
  database: catalogo_filmes_test
  username: felipe # O usuário do banco de dados para o ambiente de teste
  # Para o ambiente de teste, a senha também é opcional para setups locais.
  # Usamos ENV.fetch com um valor padrão para evitar erros se a variável não estiver definida.
  password: <%= ENV.fetch("DB_PASSWORD_TEST", "") %> # Use ENV["DB_PASSWORD_TEST"] ou vazio

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: catalogo_filmes_production
    username: catalogo_filmes # Um usuário específico e seguro para produção
    # Em produção, a senha é CRÍTICA. Usamos ENV.fetch sem um fallback,
    # o que fará o aplicativo FALHAR se a variável não estiver definida.
    # Isso é intencional para segurança.
    password: <%= ENV.fetch("CATALOGO_FILMES_DATABASE_PASSWORD") %>
    # O host do banco de dados em produção quase nunca é localhost.
    # Você deve definir DATABASE_HOST_PRODUCTION no Render.
    # Um fallback para localhost é dado, mas você deve SUBSTITUÍ-LO.
    host: <%= ENV.fetch("DATABASE_HOST_PRODUCTION", "localhost") %>
  cache:
    <<: *primary_production
    database: catalogo_filmes_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: catalogo_filmes_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: catalogo_filmes_production_cable
    migrations_paths: db/cable_migrate