# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # REMOVIDOS username e password do bloco default.
  # Eles serão definidos explicitamente em cada ambiente para evitar KeyError.
  host: localhost 

development:
  <<: *default
  database: catalogo_filmes_development
  username: felipe
  password: <%= ENV.fetch("DB_PASSWORD_TEST", "your_development_password") %> # Adicionado fallback para desenvolvimento

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: catalogo_filmes_test
  username: felipe
  password: <%= ENV.fetch("DB_PASSWORD_TEST", "a_dummy_password_for_test") %> # Já estava correto com fallback

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: catalogo_filmes_production
    username: catalogo_filmes
    # Alterado para ENV.fetch para maior segurança.
    # Em produção, se essa variável não estiver definida, é melhor que o app falhe.
    password: <%= ENV.fetch("CATALOGO_FILMES_DATABASE_PASSWORD") %>
    # Adicionado host como variável de ambiente, conforme discutido anteriormente.
    # O "localhost" é um fallback se DATABASE_HOST_PRODUCTION não estiver definido,
    # mas em produção você DEVE definir isso.
    host: <%= ENV.fetch("DATABASE_HOST_PRODUCTION", "localhost") %>
  cache:
    <<: *primary_production
    database: catalogo_filmes_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: catalogo_filmes_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: catalogo_filmes_production_cable
    migrations_paths: db/cable_migrate